image:
  file: .gitpod.Dockerfile

tasks:
  - init: yarn install
    command: yarn run start

ports:
  - port: 3000
    onOpen: notify
  - port: 3001
    onOpen: notify
  - port: 3002
    onOpen: notify
  - port: 8080

